class WaterBillRunner {
    public static void main(String[] amulya) {

        WaterBill bill = new WaterBill();

        bill.subDivision = "S12";
        bill.rrNumber = "S-258926";
        bill.consNo = 622250;
        bill.billNo = "S-4112010";
        bill.rdgDate = "01/01/2023";
        bill.dueDate = "16/01/2026";
        bill.presRdg = 3676600;
        bill.prevRdg = 3434200;
        bill.consumptionLtrs = 182000;
        bill.waterCharges = 8412.00;
        bill.meterCharges = 150.00;
        bill.sanitaryCharges = 3625.00;
        bill.scForBorewell = 200.00;
        bill.otherCharges = 6149.00;
        bill.arrears = 0.00;
        bill.interest = 0.00;
        bill.totalAmount = 18597.00;
        bill.advAmount = 0.00;
        bill.netAmountDue = 18597.00;
        bill.amountInWords = "Eighteen thousand five hundred and ninety-seven";
        System.out.println("RR No: " + bill.rrNumber);
        System.out.println("Sub Division: " + bill.subDivision);
        System.out.println("Cons No: " + bill.consNo);
        System.out.println("Bill No: " + bill.billNo);
        System.out.println("Reading Date: " + bill.rdgDate);
        System.out.println("Due Date: " + bill.dueDate);
        System.out.println("--------------------------------");
        System.out.println("Consumption Details");
        System.out.println("--------------------------------");
        System.out.println("Present Reading: " + bill.presRdg);
        System.out.println("Previous Reading: " + bill.prevRdg);
        System.out.println("Consumption (Liters): " + bill.consumptionLtrs);
        System.out.println("--------------------------------");
        System.out.println("Billing Details");
        System.out.println("--------------------------------");
        System.out.println("Water Charges: " + bill.waterCharges);
        System.out.println("Meter Charges: " + bill.meterCharges);
        System.out.println("Sanitary Charges: " + bill.sanitaryCharges);
        System.out.println("SC For Borewell: " + bill.scForBorewell);
        System.out.println("Other Charges: " + bill.otherCharges);
        System.out.println("Arrears: " + bill.arrears);
        System.out.println("Interest: " + bill.interest);
        System.out.println("Total Amount: " + bill.totalAmount);
        System.out.println("Advance Amount: " + bill.advAmount);
        System.out.println("Net Amount Due: " + bill.netAmountDue);
        System.out.println("Amount in Words: " + bill.amountInWords);

        System.out.println("--------------------------------");
		
		        WaterBill bill1 = new WaterBill();

        bill1.subDivision = "S15";
        bill1.rrNumber = "S-258927";
        bill1.consNo = 622251;
        bill1.billNo = "S-4112011";
        bill1.rdgDate = "01/02/2023";
        bill1.dueDate = "16/02/2023";
        bill1.presRdg = 3895000;
        bill1.prevRdg = 3676600;
        bill1.consumptionLtrs = 218400;
        bill1.waterCharges = 9320.00;
        bill1.meterCharges = 150.00;
        bill1.sanitaryCharges = 3800.00;
        bill1.scForBorewell = 200.00;
        bill1.otherCharges = 1200.00;
        bill1.arrears = 0.00;
        bill1.interest = 0.00;
        bill1.totalAmount = 14670.00;
        bill1.advAmount = 0.00;
        bill1.netAmountDue = 14670.00;
        bill1.amountInWords = "Fourteen thousand six hundred and seventy";

        System.out.println("RR No: " + bill1.rrNumber);
        System.out.println("Sub Division: " + bill1.subDivision);
        System.out.println("Cons No: " + bill1.consNo);
        System.out.println("Bill No: " + bill1.billNo);
        System.out.println("Reading Date: " + bill1.rdgDate);
        System.out.println("Due Date: " + bill1.dueDate);
        System.out.println("--------------------------------");
        System.out.println("Consumption Details");
        System.out.println("--------------------------------");
        System.out.println("Present Reading: " + bill1.presRdg);
        System.out.println("Previous Reading: " + bill1.prevRdg);
        System.out.println("Consumption (Liters): " + bill1.consumptionLtrs);
        System.out.println("--------------------------------");
        System.out.println("Billing Details");
        System.out.println("--------------------------------");
        System.out.println("Water Charges: " + bill1.waterCharges);
        System.out.println("Meter Charges: " + bill1.meterCharges);
        System.out.println("Sanitary Charges: " + bill1.sanitaryCharges);
        System.out.println("SC For Borewell: " + bill1.scForBorewell);
        System.out.println("Other Charges: " + bill1.otherCharges);
        System.out.println("Arrears: " + bill1.arrears);
        System.out.println("Interest: " + bill1.interest);
        System.out.println("Total Amount: " + bill1.totalAmount);
        System.out.println("Advance Amount: " + bill1.advAmount);
        System.out.println("Net Amount Due: " + bill1.netAmountDue);
        System.out.println("Amount in Words: " + bill1.amountInWords);
        System.out.println("--------------------------------");


        WaterBill bill2 = new WaterBill();

        bill2.subDivision = "S18";
        bill2.rrNumber = "S-258928";
        bill2.consNo = 622252;
        bill2.billNo = "S-4112012";
        bill2.rdgDate = "01/03/2023";
        bill2.dueDate = "16/03/2023";
        bill2.presRdg = 4102500;
        bill2.prevRdg = 3895000;
        bill2.consumptionLtrs = 207500;
        bill2.waterCharges = 8850.00;
        bill2.meterCharges = 150.00;
        bill2.sanitaryCharges = 3600.00;
        bill2.scForBorewell = 200.00;
        bill2.otherCharges = 950.00;
        bill2.arrears = 0.00;
        bill2.interest = 0.00;
        bill2.totalAmount = 13750.00;
        bill2.advAmount = 0.00;
        bill2.netAmountDue = 13750.00;
        bill2.amountInWords = "Thirteen thousand seven hundred and fifty";

        System.out.println("RR No: " + bill2.rrNumber);
        System.out.println("Sub Division: " + bill2.subDivision);
        System.out.println("Cons No: " + bill2.consNo);
        System.out.println("Bill No: " + bill2.billNo);
        System.out.println("Reading Date: " + bill2.rdgDate);
        System.out.println("Due Date: " + bill2.dueDate);
        System.out.println("--------------------------------");
        System.out.println("Consumption Details");
        System.out.println("--------------------------------");
        System.out.println("Present Reading: " + bill2.presRdg);
        System.out.println("Previous Reading: " + bill2.prevRdg);
        System.out.println("Consumption (Liters): " + bill2.consumptionLtrs);
        System.out.println("--------------------------------");
        System.out.println("Billing Details");
        System.out.println("--------------------------------");
        System.out.println("Water Charges: " + bill2.waterCharges);
        System.out.println("Meter Charges: " + bill2.meterCharges);
        System.out.println("Sanitary Charges: " + bill2.sanitaryCharges);
        System.out.println("SC For Borewell: " + bill2.scForBorewell);
        System.out.println("Other Charges: " + bill2.otherCharges);
        System.out.println("Arrears: " + bill2.arrears);
        System.out.println("Interest: " + bill2.interest);
        System.out.println("Total Amount: " + bill2.totalAmount);
        System.out.println("Advance Amount: " + bill2.advAmount);
        System.out.println("Net Amount Due: " + bill2.netAmountDue);
        System.out.println("Amount in Words: " + bill2.amountInWords);
        System.out.println("--------------------------------");


        WaterBill bill3 = new WaterBill();

        bill3.subDivision = "S20";
        bill3.rrNumber = "S-258929";
        bill3.consNo = 622253;
        bill3.billNo = "S-4112013";
        bill3.rdgDate = "01/04/2023";
        bill3.dueDate = "16/04/2023";
        bill3.presRdg = 4350000;
        bill3.prevRdg = 4102500;
        bill3.consumptionLtrs = 247500;
        bill3.waterCharges = 10150.00;
        bill3.meterCharges = 150.00;
        bill3.sanitaryCharges = 4000.00;
        bill3.scForBorewell = 200.00;
        bill3.otherCharges = 1300.00;
        bill3.arrears = 0.00;
        bill3.interest = 0.00;
        bill3.totalAmount = 15800.00;
        bill3.advAmount = 0.00;
        bill3.netAmountDue = 15800.00;
        bill3.amountInWords = "Fifteen thousand eight hundred";

        System.out.println("\nRR No: " + bill3.rrNumber);
        System.out.println("Sub Division: " + bill3.subDivision);
        System.out.println("Cons No: " + bill3.consNo);
        System.out.println("Bill No: " + bill3.billNo);
        System.out.println("Reading Date: " + bill3.rdgDate);
        System.out.println("Due Date: " + bill3.dueDate);
        System.out.println("--------------------------------");
        System.out.println("Consumption Details");
        System.out.println("--------------------------------");
        System.out.println("Present Reading: " + bill3.presRdg);
        System.out.println("Previous Reading: " + bill3.prevRdg);
        System.out.println("Consumption (Liters): " + bill3.consumptionLtrs);
        System.out.println("--------------------------------");
        System.out.println("Billing Details");
        System.out.println("--------------------------------");
        System.out.println("Water Charges: " + bill3.waterCharges);
        System.out.println("Meter Charges: " + bill3.meterCharges);
        System.out.println("Sanitary Charges: " + bill3.sanitaryCharges);
        System.out.println("SC For Borewell: " + bill3.scForBorewell);
        System.out.println("Other Charges: " + bill3.otherCharges);
        System.out.println("Arrears: " + bill3.arrears);
        System.out.println("Interest: " + bill3.interest);
        System.out.println("Total Amount: " + bill3.totalAmount);
        System.out.println("Advance Amount: " + bill3.advAmount);
        System.out.println("Net Amount Due: " + bill3.netAmountDue);
        System.out.println("Amount in Words: " + bill3.amountInWords);
        System.out.println("--------------------------------");
    }
}